- k8s_v1_persistent_volume_claim:
    name: mysql
    namespace: '{{ namespace }}'
    state: absent

- openshift_v1_deployment_config:
    name: mysql
    namespace: '{{ namespace }}'
    state: absent

- k8s_v1_service:
    name: mysql
    namespace: '{{ namespace }}'
    state: absent    

- openshift_v1_deployment_config:
    name: ups
    namespace: '{{ namespace }}'
    state: absent

- k8s_v1_service:
    name: unifiedpush
    namespace: '{{ namespace }}'
    state: absent    

- openshift_v1_route:
    name: unifiedpush
    namespace: '{{ namespace }}'
    state: absent

- k8s_v1_secret:
    name: '{{ ups_secret_name }}'
    namespace: '{{ namespace }}'
    state: absent

- k8s_v1_service_account:
    name: '{{ proxy_serviceaccount_name }}'
    namespace: '{{ namespace }}'
    state: absent